// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Dal.Contexts;

#nullable disable

namespace Restaurant.Dal.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20230605221209_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Restaurant.Dal.Entities.MenuPosition", b =>
                {
                    b.Property<Guid>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PositionId");

                    b.ToTable("MenuPositions");
                });

            modelBuilder.Entity("Restaurant.Dal.Entities.Dish", b =>
                {
                    b.HasBaseType("Restaurant.Dal.Entities.MenuPosition");

                    b.Property<string>("TypeOfDish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            PositionId = new Guid("06e0d7c2-9fbb-4c5e-b1cf-3951bba9316e"),
                            Name = "Hamburger menu 1",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/06e0d7c2-9fbb-4c5e-b1cf-3951bba9316e_updatedAt_1684869326662?updatedAt=1686002735152",
                            Price = 400m,
                            TypeOfDish = "Burger",
                            Weight = 350.0
                        },
                        new
                        {
                            PositionId = new Guid("94ba0fbc-76ec-4eac-9b48-5ff5859da457"),
                            Name = "Hamburger menu 2",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/94ba0fbc-76ec-4eac-9b48-5ff5859da457_updatedAt_1684869350144?updatedAt=1686002762114",
                            Price = 450m,
                            TypeOfDish = "Burger",
                            Weight = 400.0
                        },
                        new
                        {
                            PositionId = new Guid("860617fd-d341-41d2-a494-d982e8ae1f84"),
                            Name = "Hamburger menu 3",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/860617fd-d341-41d2-a494-d982e8ae1f84_updatedAt_1684869385003?updatedAt=1686002789666",
                            Price = 550m,
                            TypeOfDish = "Burger",
                            Weight = 450.0
                        },
                        new
                        {
                            PositionId = new Guid("a680749e-8e43-4877-9fe4-cb7b3caf130d"),
                            Name = "Hamburger menu 4",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/a680749e-8e43-4877-9fe4-cb7b3caf130d_updatedAt_1684828898277?updatedAt=1686002815166",
                            Price = 500m,
                            TypeOfDish = "Burger",
                            Weight = 400.0
                        },
                        new
                        {
                            PositionId = new Guid("78506416-6bc4-469e-9b03-1e2cf5b708a3"),
                            Name = "Steak",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/78506416-6bc4-469e-9b03-1e2cf5b708a3_updatedAt_1684828867102?updatedAt=1686002839959",
                            Price = 600m,
                            TypeOfDish = "Meat",
                            Weight = 500.0
                        },
                        new
                        {
                            PositionId = new Guid("349ac30a-ffa1-4c2f-a871-a172100d5dd7"),
                            Name = "Kebab",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/349ac30a-ffa1-4c2f-a871-a172100d5dd7_updatedAt_1684828595451?updatedAt=1686002882783",
                            Price = 400m,
                            TypeOfDish = "Meat",
                            Weight = 350.0
                        },
                        new
                        {
                            PositionId = new Guid("d0d023f5-aea2-4b19-9b18-f949b02ea87d"),
                            Name = "Nugets",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/d0d023f5-aea2-4b19-9b18-f949b02ea87d_updatedAt_1684828605346?updatedAt=1686002912137",
                            Price = 300m,
                            TypeOfDish = "Meat",
                            Weight = 250.0
                        },
                        new
                        {
                            PositionId = new Guid("c5d0bd03-f244-4429-b59c-181268153359"),
                            Name = "Salmon",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/c5d0bd03-f244-4429-b59c-181268153359_updatedAt_1684828638160?updatedAt=1686002938650",
                            Price = 600m,
                            TypeOfDish = "Fish",
                            Weight = 250.0
                        },
                        new
                        {
                            PositionId = new Guid("7bdc8f1d-6677-4065-8425-218e4c8bac36"),
                            Name = "Fried with tomato souce",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/7bdc8f1d-6677-4065-8425-218e4c8bac36_updatedAt_1684828713325?updatedAt=1686002966679",
                            Price = 700m,
                            TypeOfDish = "Fish",
                            Weight = 250.0
                        },
                        new
                        {
                            PositionId = new Guid("2a287245-da79-4f6f-9bca-29c4fd1c8b05"),
                            Name = "Grilled fish",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/2a287245-da79-4f6f-9bca-29c4fd1c8b05_updatedAt_1684828669643?updatedAt=1686002999534",
                            Price = 500m,
                            TypeOfDish = "Fish",
                            Weight = 250.0
                        },
                        new
                        {
                            PositionId = new Guid("fa744911-5fc6-486a-9cd4-3a09c539a31e"),
                            Name = "Easter fish",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/fa744911-5fc6-486a-9cd4-3a09c539a31e_updatedAt_1684828749243?updatedAt=1686003027414",
                            Price = 650m,
                            TypeOfDish = "Fish",
                            Weight = 250.0
                        },
                        new
                        {
                            PositionId = new Guid("177b95a1-8ead-4fb1-8510-9bec5c89c16a"),
                            Name = "Dorado",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/177b95a1-8ead-4fb1-8510-9bec5c89c16a_updatedAt_1684828620582?updatedAt=1686003053586",
                            Price = 400m,
                            TypeOfDish = "Fish",
                            Weight = 250.0
                        },
                        new
                        {
                            PositionId = new Guid("a23bcec4-d07c-4e6a-a131-43a064066304"),
                            Name = "Chef summer fish",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/a23bcec4-d07c-4e6a-a131-43a064066304_updatedAt_1684828784696?updatedAt=1686003079826",
                            Price = 500m,
                            TypeOfDish = "Fish",
                            Weight = 250.0
                        });
                });

            modelBuilder.Entity("Restaurant.Dal.Entities.Drink", b =>
                {
                    b.HasBaseType("Restaurant.Dal.Entities.MenuPosition");

                    b.Property<string>("TypeOfDrink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            PositionId = new Guid("cdc8e3c4-42c5-47e9-932d-5d196c04351e"),
                            Name = "Espresso",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/cdc8e3c4-42c5-47e9-932d-5d196c04351e_updatedAt_1684867378345?updatedAt=1686002415749",
                            Price = 100m,
                            TypeOfDrink = "Coffe",
                            Volume = 30.0
                        },
                        new
                        {
                            PositionId = new Guid("eb80cd9d-6586-4d76-ae91-a8e6bf5c8b5e"),
                            Name = "Cappuccino",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/eb80cd9d-6586-4d76-ae91-a8e6bf5c8b5e?updatedAt=1686002487487",
                            Price = 130m,
                            TypeOfDrink = "Coffe",
                            Volume = 50.0
                        },
                        new
                        {
                            PositionId = new Guid("cc26f172-64bd-4b14-aeca-2ffe1f7d4d63"),
                            Name = "Latte",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/cc26f172-64bd-4b14-aeca-2ffe1f7d4d63?updatedAt=1686002522820",
                            Price = 140m,
                            TypeOfDrink = "Coffe",
                            Volume = 50.0
                        },
                        new
                        {
                            PositionId = new Guid("47d6710b-32e5-429d-8723-e7971f6bef17"),
                            Name = "Orange juice",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/47d6710b-32e5-429d-8723-e7971f6bef17?updatedAt=1686002553057",
                            Price = 130m,
                            TypeOfDrink = "Juice",
                            Volume = 200.0
                        },
                        new
                        {
                            PositionId = new Guid("ab10d367-35f4-4da6-ab7f-01413eddd8d4"),
                            Name = "Apple juice",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/ab10d367-35f4-4da6-ab7f-01413eddd8d4?updatedAt=1686002586188",
                            Price = 130m,
                            TypeOfDrink = "Juice",
                            Volume = 200.0
                        },
                        new
                        {
                            PositionId = new Guid("2708e10a-b0cd-41b9-8ed2-0a8de5d864dd"),
                            Name = "Pineapple juice",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/2708e10a-b0cd-41b9-8ed2-0a8de5d864dd?updatedAt=1686002614056",
                            Price = 130m,
                            TypeOfDrink = "Juice",
                            Volume = 200.0
                        },
                        new
                        {
                            PositionId = new Guid("b46d3334-e53f-4dfa-bea9-3a1aef72d5d1"),
                            Name = "Black tea",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/b46d3334-e53f-4dfa-bea9-3a1aef72d5d1?updatedAt=1686002644091",
                            Price = 100m,
                            TypeOfDrink = "Tea",
                            Volume = 150.0
                        },
                        new
                        {
                            PositionId = new Guid("ce5db9df-0c47-4bfc-9d5f-1412cf7dc856"),
                            Name = "Green tea",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/ce5db9df-0c47-4bfc-9d5f-1412cf7dc856?updatedAt=1686002666709",
                            Price = 150m,
                            TypeOfDrink = "Tea",
                            Volume = 150.0
                        },
                        new
                        {
                            PositionId = new Guid("17a3c19e-1575-4a69-ae89-46059cce8dc7"),
                            Name = "Herbal tea",
                            PhotoLink = "https://ik.imagekit.io/7owxt4tem/17a3c19e-1575-4a69-ae89-46059cce8dc7?updatedAt=1686002693678",
                            Price = 100m,
                            TypeOfDrink = "Tea",
                            Volume = 150.0
                        });
                });

            modelBuilder.Entity("Restaurant.Dal.Entities.Dish", b =>
                {
                    b.HasOne("Restaurant.Dal.Entities.MenuPosition", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Dal.Entities.Dish", "PositionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Dal.Entities.Drink", b =>
                {
                    b.HasOne("Restaurant.Dal.Entities.MenuPosition", null)
                        .WithOne()
                        .HasForeignKey("Restaurant.Dal.Entities.Drink", "PositionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
