#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Restaurant.API/Restaurant.API.csproj", "Restaurant.API/"]
COPY ["Restaurant.Bll/Restaurant.Bll.csproj", "Restaurant.Bll/"]
COPY ["Restaurant.Dal/Restaurant.Dal.csproj", "Restaurant.Dal/"]
RUN dotnet restore "Restaurant.API/Restaurant.API.csproj"
COPY . .
WORKDIR "/src/Restaurant.API"
RUN dotnet build "Restaurant.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Restaurant.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Restaurant.API.dll"]